config/routes.rb
Rails.application.routes.draw do
  get '/contacts' => 'contacts#new'
  post '/contacts' => 'contacts#create'

  get '/sitemap', to: redirect('https://s3.amazonaws.com/bucket_name/sitemaps/sitemap.xml.gz')

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'homes#top'
  get '/corp' => 'homes#corp'
  get '/privacy' => 'homes#privacy'
  get '/sitemap' => 'homes#sitemap'

  get '/shops/search' => 'shops#search'
  post '/shops/average' => 'shops#average'
  get '/shops/places' => 'shops#places'
  resources :shops do
    resources :shop_images, only: [:index, :create, :destroy]
  end

  resources :posts, only: [:show, :edit, :update, :destroy]
  get '/:id/posts/new' => 'posts#new', as: 'shop_post_new'
  post '/:id/posts/new' => 'posts#create', as: 'shop_post_create'

  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]

  resources :places, only: [:index]

end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :shop_images, dependent: :destroy
  belongs_to :user
  accepts_attachments_for :shop_images, attachment: :image
  validates :name, presence: true, length: {maximum: 30}
  validates :station_name, length: {maximum: 20}
  validates :branch, length: {maximum: 30}
  validates :furigana, presence: true, length: {maximum: 30}, uniqueness: true
  validates :postcode, presence: true
  validates :prefecture_code, presence: true
  validates :address_city, presence: true
  validates :address_street, presence: true
  attachment :image
  attachment :head_image
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def posts
    return Post.where(shop_id: self.id)
  end

  def post
    return Post.find_by(shop_id: self.id)
  end

  def user
    return User.find(self.user_id)
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  class << self
      def within_box(distance, latitude, longitude)
          distance = distance
          center_point = [latitude, longitude]
          box = Geocoder::Calculations.bounding_box(center_point, distance)
          self.within_bounding_box(box)
      end
  end

  private
  def geocode
    uri = URI.escape("https://maps.googleapis.com/maps/api/geocode/json?address="+self.address.gsub(" ", "")+"&key=AIzaSyD_jl5PjW9qGNH6nPpOPlU4abwO09x7hzA")
    res = HTTP.get(uri).to_s
    response = JSON.parse(res)
    self.latitude = response["results"][0]["geometry"]["location"]["lat"]
    self.longitude = response["results"][0]["geometry"]["location"]["lng"]
  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:destroy]
  before_action :checked_shop, only: [:index]

  def index
    words = params[:q].delete(:station_name_or_name_or_furigana_or_other_name_or_address_city_cont) if params[:q].present?
    if words.present?
      params[:q][:groupings] = []
      words.split(/[ 　]/).each_with_index do |word, i|
        params[:q][:groupings][i] = { station_name_or_name_or_furigana_or_other_name_or_address_city_cont: word }
      end
    end
    @q = Shop.ransack(params[:q])
    @shop = @q.result(distinct: true)
  end

  def average
    @shop.each do |shop|
      if shop.posts.average(:post_total_point) != nil
        shop.total_point = shop.posts.average(:post_total_point).floor(2)
        shop.save
      end
    end
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    @shop.user_id = current_user.id
    set_address
    if @shop.save
      redirect_to shop_path(@shop), notice: "登録が完了しました"
    else
      render :new
    end
  end

  def show
    @shop = Shop.find(params[:id])
    if current_user != nil
      user_shop_post
    end
    if @shop.posts.average(:post_total_point) != nil
      @shop.total_point = @shop.posts.average(:post_total_point).floor(2)
      @shop.ave_congestion = @shop.posts.average(:congestion).floor(2)
      @shop.ave_menu = @shop.posts.average(:menu).floor(2)
      @shop.ave_price = @shop.posts.average(:price).floor(2)
      @shop.ave_wifi = @shop.posts.average(:wifi).floor(2)
      @shop.ave_others = @shop.posts.average(:others).floor(2)
    else
      @shop.total_point = nil
    end
    @post_count = 0
    @shop.posts.each do |post|
      if post.shop_id == @shop.id
        @post_count = @post_count + 1
      end
    end
    @shop.post_count = @post_count
    @shop.save
    session[:checked_shop_id] = @shop.id
    @hash = Gmaps4rails.build_markers(@shop) do |shop, marker|
      marker.lat shop.latitude
      marker.lng shop.longitude
      marker.infowindow render_to_string(partial: "shops/infowindow", locals: { shop: shop })
    end
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def update
    @shop = Shop.find(params[:id])
    set_address
    if @shop.update(shop_params)
      redirect_to shop_path(@shop.id), notice: "変更を保存しました"
    else
      render :edit
    end
  end

  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy
    redirect_to user_path(@shop.user.id), notice: "店舗情報を削除しました"
  end

  def ensure_correct_user
    @shop = Shop.find(params[:id])
    if @shop.user.id != current_user.id
      flash[:alert] = "権限がありません"
      redirect_to user_path(current_user.id)
    end
  end

  def checked_shop
    if session[:checked_shop_id] != nil
      @checked_shop = Shop.find(session[:checked_shop_id])
    end
  end

  def places
    latitude = params[:latitude].to_f
    longitude = params[:longitude].to_f
    @shops = Shop.within_box(0.621, latitude, longitude)
    @hash = Gmaps4rails.build_markers(@shops) do |shop, marker|
      marker.lat shop.latitude
      marker.lng shop.longitude
      marker.infowindow render_to_string(partial: "shops/infowindow", locals: { shop: shop })
      marker.picture({
        :url => view_context.image_path('coffee_pin.png'),
        :width   => 32,
        :height  => 32,
       })
    end
  end

  def set_address
    @shop.address = [@shop.prefecture_code,  @shop.address_city, @shop.address_street, @shop.name].compact.join
  end

  private
  def shop_params
    params.require(:shop).permit(:name, :branch, :furigana, :station_name, :other_name, :business_hour, :head_image, :postcode, :prefecture_code, :address_city, :address_street, :address_building,  shop_images_images: [])
  end

  # def search_params
  #   params.require(:q).permit(:sorts, :station_name_or_name_or_furigana_or_other_name_or_address_city_cont)
  # end

  # def search_params
  #   params.require(:q).permit(:station_name_or_name_or_furigana_or_other_name_or_address_city_cont)
  # end

  def user_shop_post
    @user_shop_post = Post.find_by(user_id: current_user.id, shop_id: @shop.id)
  end

end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_infowindow.html.erb
<%= link_to shop_path(shop) do %>
  <p class="infowindow"><%= shop.name %><%= shop.branch %></p>
  <div class="list-shop-point infowindow infowindow-point">
    <span class="point"></span>
    <% if shop.total_point != nil %>
      <%= shop.total_point%>
    <% else %>
      評価なし
    <% end %>
  </div>
<% end %>

app/views/shops/_input.html.erb
<div class="shops-new-page">
  <% if shop.errors.any? %>
  <div class="error-box" id="error_explanation">
    <h3><%= shop.errors.count %> 個のエラー</h3>
    <ul>
      <% shop.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="input-form-box">
    <div class="input-forms">
      <%= form_for shop do |f| %>
      <div class="field">
        <%= f.label "店舗名(必須)" %>
        <%= f.text_field :name, class:"input-form", placeholder:"例：スターバックスコーヒー" %>
      </div>
      <div class="field">
        <%= f.label "支店名" %>
        <%= f.text_field :branch, class:"input-form", placeholder:"例：京橋駅前店" %>
      </div>
      <div class="field">
        <%= f.label "フリガナ(必須)" %>
        <%= f.text_field :furigana, class:"input-form", placeholder:"例：スターバックスコーヒーキョウバシエキマエテン" %>
      </div>
      <div class="field">
        <%= f.label "略称、別称" %>
        <%= f.text_field :other_name, class:"input-form", placeholder:"例：スタバ" %>
      </div>
      <div class="field">
        <%= f.label "郵便番号(必須)" %>
        <%= f.text_field :postcode, class:"input-form postal_code", id: "address_zipcode", placeholder:"例：1040031" %>
      </div>
      <div class="field">
        <%= f.label "都道府県(必須)" %>
        <%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :name, :name, class: "address", selected: "東京都" %>
      </div>
      <div class="field">
        <%= f.label "市町区村(必須)" %>
        <%= f.text_field :address_city, class:"input-form",  id:"address_city", placeholder:"例：中央区" %>
      </div>
      <div class="field">
        <%= f.label "番地(必須)" %>
        <%= f.text_field :address_street, class:"input-form",  id: "address_street", placeholder:"例：京橋2-4-12" %>
      </div>
      <div class="field">
        <%= f.label "建物名・階数" %>
        <%= f.text_field :address_building, class:"input-form", placeholder:"例：京橋第一生命ビルディング1F" %>
      </div>
      <div class="field">
        <%= f.label "最寄駅" %>
        <%= f.text_field :station_name, class:"input-form", placeholder:"例：京橋" %>
      </div>
      <div class="field">
        <%= f.label "営業時間、定休日" %><br>
        <%= f.text_area :business_hour, class:"input-area", placeholder:"例：月~土[7:00~22:00] 日祝[9:00~21:00]" %>
      </div>
      <% if shop.shop_images.present? %>
      <% else %>
        <div class="field">
          <%= f.label "店舗やメニューの画像(複数選択可)" %>
          <%= f.attachment_field :shop_images_images, multiple: true, id: :shop_imgs %>
          <div class="edit-picture">
            <% shop.shop_images.each do |image| %>
              <%= attachment_image_tag image, :image, :fill, 120, 80, class: :shop_img_prev %>
            <% end %>
          </div>
          <!-- 画像プレビュー用 -->
          <script type="text/javascript">
            $(function() {
              function readURL(input) {
                  if (input.files && input.files[0]) {
                  var reader = new FileReader();
                  reader.onload = function (e) {
              $('shop_img_prev').attr('src', e.target.result);
                  }
                  reader.readAsDataURL(input.files[0]);
                  }
              }
              $("#shop_imgs").change(function(){
                  readURL(this);
              });
            });
          </script>
          <!-- 画像プレビュー用 -->
        </div>
      <% end %>
      <div class="field">
        <%= f.label "検索結果に表示するお店の画像(1枚)" %>
        <%= f.attachment_field :head_image, id: :head_img %>
        <div class="edit-picture">
          <% if @shop.head_image.present? %>
          <%= attachment_image_tag shop, :head_image, :fill, 120, 80, id: :head_img_prev %>
          <% else %>
          <%= image_tag 'no_image.png', size: '120x80', id: :head_img_prev %>
          <% end %>
        </div>
        <!-- 画像プレビュー用 -->
        <script type="text/javascript">
          $(function() {
            function readURL(input) {
                if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
            $('#head_img_prev').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
                }
            }
            $("#head_img").change(function(){
                readURL(this);
            });
          });
        </script>
        <!-- 画像プレビュー用 -->
      </div>
      <div class="actions">
        <%= f.submit "登録", class:"btn-sticky" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shops/edit.html.erb
<% breadcrumb :edit_shop, @shop %>
<div class="page-title">
  <h1>店舗編集</h1>
</div>
<%= render 'input', shop: @shop %>

app/views/shops/index.html.erb
<% breadcrumb :shops %>
<div class="shop-search-page">
    <div class="page-title">
        <h1>店名・駅名から探す</h1>
    </div>
    <div class="narrow-window">
        <div class="search-field">
            <%= search_form_for @q, url: shops_path do |f| %>
            <!-- <div> -->
            <%#<%= f.select :sorts, {"評価点順": "total_point desc", "登録順": "id desc", "レビュー数順": "post_count desc"} %>
            <!-- </div> -->
            <%= f.search_field :station_name_or_name_or_furigana_or_other_name_or_address_city_cont, class:"input-form" %>
            <%= f.submit "検索", class:"btn-sticky" %>
            <% end %>
        </div>
        <div class="candidate-lists">
            <% if request.url.match(/commit/) %>
            <% @shop.each do |shop| %>
            <%= link_to shop_path(shop), class:"candidate-list" do %>
            <% if shop.head_image.present? %>
            <%= attachment_image_tag shop, :head_image, :fill, 120, 90,class:"list-img" %>
            <% else %>
            <%= image_tag 'no_image.png', size: '125x95', class:"list-img" %>
            <% end %>
            <div class="shop-infos">
                <div class="shop-name">
                    <div class="shop-name-inner">
                        <%= shop.name %><%= shop.branch %>
                    </div>
                </div>
                <% if shop.total_point %>
                <div class="list-shop-point">
                    <span class="point"><%= shop.total_point%></span>
                </div>
                <% end %>
            </div>
            <% end %>
            <% end %>
            <% else %>
            <% if @checked_shop != nil %>
            最近チェックしたお店
            <%= link_to shop_path(@checked_shop.id), class:"candidate-list" do %>
            <% if @checked_shop.head_image.present? %>
            <%= attachment_image_tag @checked_shop, :head_image, :fill, 120, 90,class:"list-img" %>
            <% else %>
            <%= image_tag 'no_image.png', size: '120x90', class:"list-img" %>
            <% end %>
            <div class="shop-infos">
                <div class="shop-name">
                    <p><%= @checked_shop.name %><br><%= @checked_shop.branch %></p>
                </div>
                <% if @checked_shop.total_point %>
                <div class="list-shop-point">
                    <span class="point"><%= @checked_shop.total_point%></span>
                </div>
                <% end %>
            </div>
            <% end %>
            <% end %>
            最近登録された店舗
            <% @shop.reverse_order.first(5).each do |shop| %>
            <%= link_to shop_path(shop), class:"candidate-list" do %>
            <% if shop.head_image.present? %>
            <%= attachment_image_tag shop, :head_image, :fill, 120, 90,class:"list-img" %>
            <% else %>
            <%= image_tag 'no_image.png', size: '125x95', class:"list-img" %>
            <% end %>
            <div class="shop-infos">
                <div class="shop-name">
                    <div class="shop-name-inner">
                        <%= shop.name %><%= shop.branch %>
                    </div>
                </div>
                <% if shop.total_point %>
                <div class="list-shop-point">
                    <span class="point"><%= shop.total_point%></span>
                </div>
                <% end %>
            </div>
            <% end %>
            <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/shops/new.html.erb
<% breadcrumb :new_shop %>
<div class="page-title">
  <h1>店舗登録</h1>
</div>
<%= render 'input', shop: @shop %>

app/views/shops/places.html.erb
<% breadcrumb :shop_places %>
<div class="shop-place-page">
  <div style='100vw;'>
    <div id="map" style=''>
    </div>
    <div class="shop-search-button">
      <button class="btn-sticky" onclick="getPosition();"><p>近くのお店を<br>探す</p></button>
    </div>
  </div>
  <script>
    //gmaps4rails
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%= raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(15);
      if(navigator.geolocation)
      navigator.geolocation.getCurrentPosition(displayOnMap);
    });
    function displayOnMap(position){
      var marker = handler.addMarker({
        lat: position.coords.latitude,
        lng: position.coords.longitude
      });
      handler.map.centerOn(marker);
      var circles = handler.addCircles(
        [{lat: position.coords.latitude,
          lng: position.coords.longitude,
          radius: 1000 }],
        { strokeColor: '#fcba03'}
      );
      handler.bounds.extendWith(circles);
    };
    //gmaps4rails
    // 現在地取得処理
    function getPosition() {
      // 現在地を取得
      navigator.geolocation.getCurrentPosition(
        // 取得成功した場合
        function(position) {
            window.location.href = "/shops/places?latitude="+position.coords.latitude+"&longitude="+position.coords.longitude
            // $.ajax({
            //     url: "/shops/places",
            //     type: "GET",
            //     dataType: 'html',
            //     data: {latitude : position.coords.latitude,
            //           longitude : position.coords.longitude},
            //       }).then(function(response){
            //   console.log(response);
            // })
        },
        // 取得失敗した場合
        function(error) {
          switch(error.code) {
            case 1: //PERMISSION_DENIED
              alert("位置情報の利用が許可されていません");
              break;
            case 2: //POSITION_UNAVAILABLE
              alert("現在位置が取得できませんでした");
              break;
            case 3: //TIMEOUT
              alert("タイムアウトになりました");
              break;
            default:
              alert("その他のエラー(エラーコード:"+error.code+")");
              break;
          }
        }
      );
    }
  </script>
</div>

app/views/shops/show.html.erb
<% breadcrumb :shop, @shop %>
<div class="shop-info-page">
  <div class="page-title">
    <h1>店舗情報</h1>
  </div>
  <div class="shop-main-info">
    <h2><%= @shop.name %><br><%= @shop.branch %></h2>
    <div class="star" id="star-rate-shop-<%= @shop.id %>"></div>
    <p class="star-number"><%= @shop.total_point %></p>
    <script>
    $('#star-rate-shop-<%= @shop.id %>').raty({
      size: 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      half: true,
      readOnly: true,
      score: <%= @shop.total_point %>,
    });
    </script>
  </div>
  <div class="shop-imgs">
    <div class="shop-img">
      <% if @shop.shop_images.present? %>
        <% @shop.shop_images.first(3).each_with_index do |image, index| %>
          <% if index===0 %>
            <input type="radio" id="img-<%= index %>" name="img-switch" checked>
          <% else %>
            <input type="radio" id="img-<%= index %>" name="img-switch">
          <% end %>
          <label for="img-<%= index %>"><%= attachment_image_tag image, :image, :fill, 60, 45 %></label>
          <%= link_to shop_shop_images_path(@shop.id) do %>
            <%= attachment_image_tag image, :image, :fill, 400, 300, class:"slide-img" %>
          <% end %>
        <% end %>
      <% else %>
        <%= image_tag 'no_image.png', size: '400x300', class:"slide-img" %>
      <% end %>
    </div>
  </div>
  <div class="shop-info-details">
    <div class="table-line">
      <div class="table-left">
        <p>営業時間</p>
      </div>
      <div class="table-center">
        <p>:</p>
      </div>
      <div class="table-right">
        <p><%= @shop.business_hour %></p>
      </div>
    </div>
    <div class="table-line">
      <div class="table-left">
        <p>最寄駅</p>
      </div>
      <div class="table-center">
        <p>:</p>
      </div>
      <div class="table-right">
        <p><%= @shop.station_name %></p>
      </div>
    </div>
    <div class="table-line">
      <div class="table-left">
        <p>混み具合</p>
      </div>
      <div class="table-center">
        <p>:</p>
      </div>
      <div class="table-right">
        <div class="star" id="star-rate-shop-congestion-<%= @shop.id %>"></div>
        <script>
        $('#star-rate-shop-congestion-<%= @shop.id %>').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= @shop.ave_congestion %>,
        });
        </script>
        <p><%= @shop.ave_congestion %></p>
      </div>
    </div>
    <div class="table-line">
      <div class="table-left">
        <p>メニュー</p>
      </div>
      <div class="table-center">
        <p>:</p>
      </div>
      <div class="table-right">
        <div class="star" id="star-rate-shop-menu-<%= @shop.id %>"></div>
        <script>
        $('#star-rate-shop-menu-<%= @shop.id %>').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= @shop.ave_menu %>,
        });
        </script>
        <p><%= @shop.ave_menu %></p>
      </div>
    </div>
    <div class="table-line">
      <div class="table-left">
        <p>価格帯</p>
      </div>
      <div class="table-center">
        <p>:</p>
      </div>
      <div class="table-right">
        <div class="star" id="star-rate-shop-price-<%= @shop.id %>"></div>
        <script>
        $('#star-rate-shop-price-<%= @shop.id %>').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= @shop.ave_price %>,
        });
        </script>
        <p><%= @shop.ave_price %></p>
      </div>
    </div>
    <div class="table-line">
      <div class="table-left">
        <p>通信環境</p>
      </div>
      <div class="table-center">
        <p>:</p>
      </div>
      <div class="table-right">
        <div class="star" id="star-rate-shop-wifi-<%= @shop.id %>"></div>
        <script>
        $('#star-rate-shop-wifi-<%= @shop.id %>').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= @shop.ave_wifi %>,
        });
        </script>
        <p><%= @shop.ave_wifi %></p>
      </div>
    </div>
    <div class="table-line">
      <div class="table-left">
        <p>その他</p>
      </div>
      <div class="table-center">
        <p>:</p>
      </div>
      <div class="table-right">
        <div class="star" id="star-rate-shop-others-<%= @shop.id %>"></div>
        <script>
        $('#star-rate-shop-others-<%= @shop.id %>').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= @shop.ave_others %>,
        });
        </script>
        <p><%= @shop.ave_others %></p>
      </div>
    </div>
    <div class="table-line">
      <div class="table-left">
        <p>評価数</p>
      </div>
      <div class="table-center">
        <p>:</p>
      </div>
      <div class="table-right">
        <p><%= @post_count %>件</p>
      </div>
    </div>
    <div class="shop-edit-name">
      <% if current_user != nil %>
        <%= link_to "編集", edit_shop_path(@shop.id) %>
      <% end %>
      <p>written by <span class="written-name"><%= @shop.user.name %></span></p>
    </div>
    <!-- Googlemap -->
    <div class="shop-place">
      <h3>住所</h3>
      <p><%= @shop.prefecture_code %><%= @shop.address_city %><%= @shop.address_street %><%= @shop.address_building %></p>
      <div class="google-map">
        <div id="map" style="width: inherit; height: 200px;"></div>
        <script>
          handler = Gmaps.build('Google');
          handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
            markers = handler.addMarkers(<%= raw @hash.to_json %>);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
            handler.getMap().setZoom(17);
          });
        </script>
      </div>
    </div>
    <!-- Googlemap -->
    <!-- 投稿一覧 -->
    <div class="reviews-list">
      <h3>レビュー</h3>
      <div class="review-new-link">
        <% if current_user != nil %>
          <% if @user_shop_post == nil %>
            <%= link_to "レビューを書く", "/#{@shop.id}/posts/new" %>
          <% else %>
            <%= link_to "レビューを書く", edit_post_path(@user_shop_post.id) %>
          <% end %>
        <% else %>
          <%= link_to "レビューを書く",  new_user_registration_path %>
        <% end %>
      </div>
      <% @shop.posts.each do |post| %>
        <div class="review">
          <div class="review-name">
            <h4><%= post.user.name %></h4>
          </div>
          <div class="star" id="star-rate-post-<%= post.id %>"></div>
          <script>
          $('#star-rate-post-<%= post.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= post.post_total_point %>,
          });
          </script>
          <div class="review-total-point">
            <p><%= post.post_total_point %></p>
          </div>
          <div class="review-point-details">
            <div class="point-line">
              <div class="point-left">
                <p>混み具合</p>
              </div>
              <div class="point-center">
              <p>:</p>
              </div>
              <div class="point-right">
                <p><%= post.congestion %></p>
              </div>
            </div>
            <div class="point-line">
              <div class="point-left">
                <p>メニュー</p>
              </div>
              <div class="point-center">
              <p>:</p>
              </div>
              <div class="point-right">
                <p><%= post.menu %></p>
              </div>
            </div>
            <div class="point-line">
              <div class="point-left">
                <p>価格帯</p>
              </div>
              <div class="point-center">
              <p>:</p>
              </div>
              <div class="point-right">
                <p><%= post.price %></p>
              </div>
            </div>
            <div class="point-line">
              <div class="point-left">
                <p>通信環境</p>
              </div>
              <div class="point-center">
              <p>:</p>
              </div>
              <div class="point-right">
                <p><%= post.wifi %></p>
              </div>
            </div>
            <div class="point-line">
              <div class="point-left">
                <p>その他</p>
              </div>
              <div class="point-center">
              <p>:</p>
              </div>
              <div class="point-right">
                <p><%= post.others %></p>
              </div>
            </div>
          </div>
          <div class="review-text">
            <p><%= post.review %></p>
          </div>
        </div>
      <% end %>
    </div>
    <!-- 投稿一覧 -->
  </div>
</div>