config/routes.rb
Rails.application.routes.draw do
  get '/contacts' => 'contacts#new'
  post '/contacts' => 'contacts#create'

  get '/sitemap', to: redirect('https://s3.amazonaws.com/bucket_name/sitemaps/sitemap.xml.gz')

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'homes#top'
  get '/corp' => 'homes#corp'
  get '/privacy' => 'homes#privacy'
  get '/sitemap' => 'homes#sitemap'

  get '/shops/search' => 'shops#search'
  post '/shops/average' => 'shops#average'
  get '/shops/places' => 'shops#places'
  resources :shops do
    resources :shop_images, only: [:index, :create, :destroy]
  end

  resources :posts, only: [:show, :edit, :update, :destroy]
  get '/:id/posts/new' => 'posts#new', as: 'shop_post_new'
  post '/:id/posts/new' => 'posts#create', as: 'shop_post_create'

  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]

  resources :places, only: [:index]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, dependent: :destroy
  has_many :shops
  validates :name, presence: true, length: {in:2..20}
  attachment :profile_image

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user.id), notice: "変更を保存しました"
    else
      render :edit
    end
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
      flash[:alert] = "権限がありません"
      redirect_to user_path(current_user.id)
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% breadcrumb :edit_user, @user %>
<div class="user-edit-page">
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h3><%= @user.errors.count %> 個のエラー</h3>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="page-title">
    <h1>プロフィール編集</h1>
  </div>
  <div class="input-form-box">
    <div class="input-forms">
      <%= form_for @user do |f| %>
        <div class="field">
          <%= f.label :name %><br />
          <%= f.text_field :name, autofocus: true, class:"input-form" %>
        </div>

        <div class="field">
          <%= f.label :profile_image %>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", id: :profile_img %>
          <% if @user.profile_image.present? %>
            <%= attachment_image_tag @user, :profile_image, :fill, 80, 80, id: :img_prev %>
          <% else %>
            <%= image_tag 'no_image.jpg', size: '80x80', id: :img_prev %>
          <% end %>
          <!-- 画像プレビュー用 -->
          <script type="text/javascript">
            $(function() {
              function readURL(input) {
                  if (input.files && input.files[0]) {
                  var reader = new FileReader();
                  reader.onload = function (e) {
              $('#img_prev').attr('src', e.target.result);
                  }
                  reader.readAsDataURL(input.files[0]);
                  }
              }
              $("#profile_img").change(function(){
                  readURL(this);
              });
            });
          </script>
          <!-- 画像プレビュー用 -->
        </div>

        <div class="actions">
          <%= f.submit "保存", class:"btn-sticky" %>
        </div>
      <% end %>
    </div>
    <div class="links">
      <%= link_to "アカウント編集はこちら", edit_user_registration_path %>
    </div>
  </div>
  </div>

app/views/users/show.html.erb
<% breadcrumb :user, @user %>
<div class="my-page">
  <div class="page-title">
    <h1>マイページ</h1>
  </div>
  <div class="narrow-window">
    <div class="my-info">
        <% if @user.profile_image.present? %>
          <%= attachment_image_tag @user, :profile_image, :fill, 80, 80 %>
        <% else %>
          <%= image_tag 'no_image.png', size: '80x80' %>
        <% end %>
      <div class="my-info-bottom">
        <div class="my-name">
          <h3><%= @user.name %></h3>
        </div>
        <% if current_user != nil %>
          <% if @user.id == current_user.id %>
            <div class="my-info-edit-link">
              <%= link_to "プロフィールの編集", edit_user_path %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="shop-lists">
      <div class="reviewed-shops">
        <label for="label1" class="reviewed-shops-title">
          <h4>レビューした店舗</h4>
        </label>
        <input type="checkbox" id="label1" class="reviewed-shop-checkbox"/>
        <div class="reviewed-shops-list">
          <% @user.posts.order(created_at: :desc).each do |post| %>
          <div class="reviewed-shop">
            <div class="reviewed-shop-inner">
              <div class="reviewed-shop-main-info">
                <%= link_to shop_path(post.shop_id) do %>
                  <div class="reviewed-shop-name">
                    <h5><%= post.shop.name %><br><%= post.shop.branch %></h5>
                  </div>
                  <div class="reviewed-shop-point">
                    <p>総合評価</p>
                    <p><%= post.post_total_point %></p>
                    <div id="star-rate-post-<%= post.id %>"></div>
                    <script>
                    $('#star-rate-post-<%= post.id %>').raty({
                      size: 36,
                      starOff:  '<%= asset_path('star-off.png') %>',
                      starOn : '<%= asset_path('star-on.png') %>',
                      starHalf: '<%= asset_path('star-half.png') %>',
                      half: true,
                      readOnly: true,
                      score: <%= post.post_total_point %>,
                    });
                    </script>
                  </div>
                <% end %>
              </div>
              <div class="reviewed-shop-sub-info">
                <%= link_to post_path(post.id) do %>
                  <div class="sub-info">
                    <p><span class="sub-info-left">混み具合</span><span class="sub-info-center">:</span><%= post.congestion %></p>
                  </div>
                  <div class="sub-info">
                    <p><span class="sub-info-left">メニュー</span><span class="sub-info-center">:</span><%= post.menu %></p>
                  </div>
                  <div class="sub-info">
                    <p><span class="sub-info-left">価格帯</span><span class="sub-info-center">:</span><%= post.price %></p>
                  </div>
                  <div class="sub-info">
                    <p><span class="sub-info-left">通信環境</span><span class="sub-info-center">:</span><%= post.wifi %></p>
                  </div>
                  <div class="sub-info">
                    <p><span class="sub-info-left">その他</span><span class="sub-info-center">:</span><%= post.others %></p>
                  </div>
                  <div class="sub-info">
                    <p><span class="sub-info-left">レビュー</span><span class="sub-info-center">:</span><%= post.review.truncate(15) %></p>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="reviewed-edit-delete">
              <% if current_user != nil %>
              <% if post.user.id == current_user.id %>
                <%= link_to "編集", edit_post_path(post.id) %>
                |
                <%= link_to "削除", post_path(post), method: :delete, data: {confirm: "本当に削除しますか？"} %>
              <% end %>
              <% end %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
      <div class="registered-shops">
        <label for="label2" class="registered-shops-title">
          <h4>登録した店舗</h4>
        </label>
        <input type="checkbox" id="label2" class="registered-shop-checkbox" />
        <div class="registered-shops-list">
          <% @user.shops.order(created_at: :desc).each do |shop| %>
            <div class="registered-shop">
              <div class="registered-shop-inner">
                <%= link_to shop_path(shop.id), class:"registered-shop-main-info" do %>
                  <div class="registered-shop-name">
                    <h5><%= shop.name %><br><%= shop.branch %></h5>
                  </div>
                  <div class="registered-shop-furigana">
                    <p><%= shop.furigana %></p>
                  </div>
                <% end %>
                <div class="registered-shop-sub-info">
                  <div class="sub-info">
                    <p><span class="sub-info-left">最寄駅</span><span class="sub-info-center">:</span><%= shop.station_name %></p>
                  </div>
                  <div class="sub-info">
                    <p><span class="sub-info-left">略称・別称</span><span class="sub-info-center">:</span><%= shop.other_name %></p>
                  </div>
                  <div class="sub-info">
                    <p><span class="sub-info-left">住所</span><span class="sub-info-center">:</span>
                    <span class="sub-info-right"><%= shop.prefecture_code %><%= shop.address_city %><%= shop.address_street %><%= shop.address_building %></span></p>
                  </div>
                </div>
              </div>
              <div class="registered-edit-delete">
                <% if current_user != nil %>
                <% if shop.user.id == current_user.id %>
                  <%= link_to "編集", edit_shop_path(shop.id) %>
                  |
                  <%= link_to "削除", shop_path(shop), method: :delete, data: {confirm: "本当に削除しますか？"} %>
                <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>