config/routes.rb
Rails.application.routes.draw do
  get '/contacts' => 'contacts#new'
  post '/contacts' => 'contacts#create'

  get '/sitemap', to: redirect('https://s3.amazonaws.com/bucket_name/sitemaps/sitemap.xml.gz')

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'homes#top'
  get '/corp' => 'homes#corp'
  get '/privacy' => 'homes#privacy'
  get '/sitemap' => 'homes#sitemap'

  get '/shops/search' => 'shops#search'
  post '/shops/average' => 'shops#average'
  get '/shops/places' => 'shops#places'
  resources :shops do
    resources :shop_images, only: [:index, :create, :destroy]
  end

  resources :posts, only: [:show, :edit, :update, :destroy]
  get '/:id/posts/new' => 'posts#new', as: 'shop_post_new'
  post '/:id/posts/new' => 'posts#create', as: 'shop_post_create'

  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]

  resources :places, only: [:index]

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end
  
  def corp
    
  end

  def sitemap
    
  end
  
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/corp.html.erb
<div class="corp-page">
  <div class="corp-title">
    <p>開発者プロフィール</p>
  </div>
  <div class="corp-items">
    <div class="corp-item">
      <p>福田悠吾</p>
      <p>東京理科大学工学部情報工学科在籍</p>
      <p>サーバーサイドエンジニア</p>
    </div>
    <div class="corp-item">
      <p>佐藤貫平</p>
      <p>東京理科大学工学部情報工学科在籍</p>
      <p>フロントエンドエンジニア</p>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="top-page">
  <div class="main-window">
    <div class="page-title">
      <h1>お店を探す</h1>
    </div>
    <div class="search-box">
      <div class="search-box-item">
          <%= link_to "店名・駅名から探す", shops_path , class:"select-circle select-station"%>
      </div>
      <div class="search-box-item">
        <%= link_to "位置情報から探す", shops_places_path , class:"select-circle select-map"%>
      </div>
    </div>
    <a href="#about">
      <div class="about-link">
        <h2>Kissaとは</h2>
        <h2>Click</h2>
      </div>
    </a>
  </div>
  <div class="about-page">
    <div class="article-1">
      <div class="article-image">
        <a name="about"></a>
      </div>
      <div class="article-1-1">
        <div class="article-1-1-inner">
          <div class="article-1-1-title">
            <h3 class="title title-k">K</h3>
            <h3 class="title title-i">i</h3>
            <h3 class="title title-s-1">s</h3>
            <h3 class="title title-s-2">s</h3>
            <h3 class="title title-a">a</h3>
          </div>
          <div class="article-1-1-text">
            <p>今日のカフェを、見つけるアプリ。</p>
          </div>
        </div>
      </div>
      <%# <div class="article-border">
        <div class="article-border-inner">
        </div>
      </div> %>
    </div>
    <div class="article-2">
      <div class="article-image">
        <div class="article-2-infos">
          <div class="article-2-infos-inner">
          <div class="article-2-nologin">
            <div class="touch-click-back">
              <p>Touch</p>
            </div>
            <div class="article-2-nologin-info">
              <div class="article-2-nologin-info-title">
                <h4>ログインせずに使える機能</h4>
              </div>
              <div class="article-2-nologin-info-list">
                <div class="article-2-nologin-info-list-item">
                  <h5>1. 店名、駅名からカフェを探す</h5>
                  <p>キーワードを入力し検索すれば、世界中の人たちが見つけたカフェから最適なお店を探し出すことができます。</p>
                </div>
                <div class="article-2-nologin-info-list-item">
                  <h5>2. 位置情報からカフェを探す</h5>
                  <p>Kissaがあなたの現在地を取得し、お近くの最適なカフェをすぐに見つけ出します。</p>
                </div>
              </div>
            </div>
          </div>
          </div>
          <div class="article-2-login">
            <div class="touch-click-back">
              <p>Touch</p>
            </div>
            <div class="article-2-login-info">
              <div class="article-2-login-info-title">
                <h4>ログインしたら使える機能</h4>
              </div>
              <div class="article-2-login-info-list">
                <div class="article-2-login-info-list-item">
                  <h5>1. レビューを投稿</h5>
                  <p>気に入ったカフェをレビューして、世界中の人たちに教えてあげることができます。</p>
                </div>
                <div class="article-2-login-info-list-item">
                  <h5>2. 新しいカフェの登録</h5>
                  <p>まだ誰も知らない隠れ家カフェを見つけて、パイオニアになりましょう。</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="article-3">
      <div class="article-3-top">
        <div class="article-3-top-space">
        </div>
        <div class="article-3-top-text">
          <h6>今日のカフェを<br>見つけよう。</h6>
        </div>
        <div class="article-3-top-picture">
          <div class="article-3-top-picture-left">
            <div class="article-3-top-picture-left-top">
            </div>
          </div>
          <div class="article-3-top-picture-right">
          </div>
        </div>
      </div>
      <div class="article-3-bottom">
        <%= link_to shops_path, class:"article-3-bottom-link" do %>
          <span>店名・駅名から探す</span>
        <% end %>
        <%= link_to shops_places_path, class:"article-3-bottom-link" do %>
          <span>位置情報から探す</span>
        <% end %>
      </div>
    </div>
  </div>
</div>