config/routes.rb
Rails.application.routes.draw do
  get '/contacts' => 'contacts#new'
  post '/contacts' => 'contacts#create'

  get '/sitemap', to: redirect('https://s3.amazonaws.com/bucket_name/sitemaps/sitemap.xml.gz')

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'homes#top'
  get '/corp' => 'homes#corp'
  get '/privacy' => 'homes#privacy'
  get '/sitemap' => 'homes#sitemap'

  get '/shops/search' => 'shops#search'
  post '/shops/average' => 'shops#average'
  get '/shops/places' => 'shops#places'
  resources :shops do
    resources :shop_images, only: [:index, :create, :destroy]
  end

  resources :posts, only: [:show, :edit, :update, :destroy]
  get '/:id/posts/new' => 'posts#new', as: 'shop_post_new'
  post '/:id/posts/new' => 'posts#create', as: 'shop_post_create'

  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]

  resources :places, only: [:index]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Kissa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//maps.googleapis.com/maps/api/js?key=AIzaSyD_jl5PjW9qGNH6nPpOPlU4abwO09x7hzA"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Kissa">
    <link rel="apple-touch-icon" href="<%= image_url("pwa-120.png") %>" sizes="120x120">
    <!-- Google Adsense -->
    <script data-ad-client="ca-pub-8476733040094557" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-161478987-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-161478987-1');
    </script>
</head>

<body data-turbolinks="false" , ontouchstart="">
    <!-- メニューバー -->
    <header>
        <h1><%= link_to "Kissa", root_path, class:"title" %></h1>
        <ul class="nav-list">
            <% if user_signed_in? %>
            <li class="nav-list-item"><%= link_to "店舗検索", root_path %></li>
            <li class="nav-list-item"><%= link_to "店舗登録", new_shop_path %></li>
            <li class="nav-list-item"><%= link_to "マイページ", user_path(current_user) %></li>
            <li class="nav-list-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li class="nav-list-item"><%= link_to "店舗検索", root_path %></li>
            <li class="nav-list-item"><%= link_to "ログイン", new_user_session_path %></li>
            <li class="nav-list-item"><%= link_to "新規登録", new_user_registration_path %></li>
            <% end %>
        </ul>
        <div class="nav-drawer">
            <input class="nav-input" type="checkbox" id="nav-menu">
            <label class="nav-open" for="nav-menu"><span></span></label>
            <label class="nav-close-1" for="nav-menu"><span></span></label>
            <div class="nav-content">
                <label class="nav-close-2" for="nav-menu"><span></span></label>
                <div class="nav-title">
                    <p>Menu</p>
                </div>
                <div class="nav-items">
                    <% if user_signed_in? %>
                    <%= link_to "店舗検索", root_path %>
                    <%= link_to "店舗登録", new_shop_path %>
                    <%= link_to "マイページ", user_path(current_user) %>
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                    <% else %>
                    <%= link_to "店舗検索", root_path %>
                    <%= link_to "ログイン", new_user_session_path %>
                    <%= link_to "新規登録", new_user_registration_path %>
                    <% end %>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <% if flash[:notice] %>
        <div class="flash">
            <%= flash[:notice] %>
        </div>
        <% end %>
        <% if flash[:alert] %>
        <div class="flash">
            <%= flash[:alert] %>
        </div>
        <% end %>
        <!-- パンくずリスト -->
        <%= breadcrumbs separator: " &rsaquo; " %>
        <%= yield %>
        <footer>
            <div class="footer-inner">
              <div class="footer-link">
                <%= link_to  "運営者情報", corp_path %>
                <%= link_to  "プライバシーポリシー", asset_path("privacy.pdf") %>
                <%= link_to  "お問い合せ", contacts_path %>
              </div>
              <div class="footer-copyright">
                <p>Copyright © Kissa. All Rights Reserved.</p>
              </div>
            </div>
        </footer>
    </div>
</body>

</html>